<?php

namespace Database\Seeders;

use App\Models\Employee;
use Illuminate\Database\Seeder;

class EmployeeSeeder extends Seeder
{
    public function run(): void
    {
        $csv = <<<'CSV'
DIZON,GINA PAULA D.,Administrative Aide VI,5,OMSD,Casual,
ARNEJO,RALIEN NEIL A.,Administrative Aide IV (Driver II),5,GSU,Casual,
BALURAN,ANTHONY P.,Courier,5,GSU,Casual,
CABALLERO,CHARLES G.,Social Insurance Assistant I,6,GSU,Casual,
MIPANGCAT,OMAR A.,Driver II,5,GSU,Casual,
MORENO,CELMOR M.,Driver II,5,GSU,Casual,
TAN,IKE JAMES R.,Driver II,5,GSU,Casual,
DE LOS REYES,ROSETTE JIN G.,Social Insurance Assistant I,6,HRU,Casual,
RANDA,CHARON L.,Administrative Aide VI,5,HRU,Casual,
ABADAY,NELL REXTER L.,Administrative Aide VI,5,CU,Casual,
ESTAÑA,NOELLE KRISTIE M.,Administrative Aide VI,5,CU,Casual,
MAMA,NAMRAIDA M.,Social Insurance Assistant I,6,CU,Casual,
SOLAIMAN,ABDUL BARI M.,Administrative Aide VI,5,CU,Casual,
TOMAWIS,NADRA C.,Social Insurance Assistant I,6,CU,Casual,
ALFECHE,JESSON P.,Social Insurance Assistant I,6,CU,Casual,
BAYRON,RAE ANGELIQUE G.,Administrative Aide VI,5,OHCDMD,Casual,
HADJINASSER,NORHAYA U.,Administrative Aide VI,5,OHCDMD,Casual,
ISIDTO-BETE,MAYVEL T.,Administrative Aide VI,5,OHCDMD,Casual,
ABLANQUE,HAROLD B.,Administrative Aide VI,5,BAS,Casual,
AGAPAY,JUDITH MARIE D.,Administrative Aide VI,5,BAS,Casual,
ALONTO,AMEURPINA G.,Courier,5,BAS,Casual,
BACOMO,EMEE D.,Administrative Aide VI,5,BAS,Casual,
BINT-MUBARAK,ANNA NORAYA,Administrative Aide VI,5,BAS,Casual,
DICKA,SHEILA A.,Social Insurance Assistant I,6,BAS,Casual,
EBAJAY,NORMAN Q.,Administrative Aide VI,5,BAS,Casual,
ELIZAGA,DAISYBEL V.,Administrative Aide VI,5,BAS,Casual,
FABELLO,ARISTOTLE MOLAVE C.,Social Insurance Assistant I,6,BAS,Casual,
FABELLO,CHARISSE A.,Administrative Aide VI,5,BAS,Casual,
FAROUK-RIPORS,SOHAILA M.,Courier,5,BAS,Casual,
HADJI NASSER,MOHAMMAD FARHAN D.,Administrative Aide VI,5,BAS,Casual,
MANONG,VINCENT S.,Courier,5,BAS,Casual,
MATALANG,KENNETH MICHAEL P.,Administrative Aide VI,5,BAS,Casual,
OLAMA,FATMA ALANA S.,Courier,5,BAS,Casual,
OMICTIN,LOVELY PEARL C.,Administrative Aide VI,5,BAS,Casual,
PACAS,MARY LOU M.,Administrative Aide VI,5,BAS,Casual,
PANDI,ASLIMAH L.,Administrative Aide VI,5,BAS,Casual,
PEREZ,DEBCILLE O.,Administrative Aide VI,5,BAS,Casual,
PILO,HANNAH MAE D.,Administrative Aide VI,5,BAS,Casual,
REVAÑO,ANNELYN R.,Administrative Aide VI,5,BAS,Casual,
SAMBARANI,SAMARATUL AINIE N.,Administrative Aide VI,5,BAS,Casual,
RATERTA,REYNELEN L.,Courier,5,AQAS,Casual,
SANTOS,ZECIELA B.,Administrative Aide VI,5,AQAS,Casual,
ACAIN,JULIE ANN V.,Social Insurance Assistant I,6,PCARES,Casual,
APAT,MARY CARMEL F.,Social Insurance Assistant I,6,PCARES,Casual,
BACOR,CHASSY A.,Social Insurance Assistant I,6,PCARES,Casual,
CABANG,LOUIEMAR Y.,Social Insurance Assistant I,6,PCARES,Casual,
CIRERA,MARLON G.,Social Insurance Assistant I,6,PCARES,Casual,
DOMINGO,FEBREL P.,Social Insurance Assistant I,6,PCARES,Casual,
GOMEZ,LUCILLE ALLEN D.,Social Insurance Assistant I,6,PCARES,Casual,
HURAÑO,MARY ANN A.,Social Insurance Assistant I,6,PCARES,Casual,
LAGUMBAY,ALVIN JOHN S.,Social Insurance Assistant I,6,PCARES,Casual,
LOZADA,MAY RACHELLE C.,Social Insurance Assistant I,6,PCARES,Casual,
MACAGAAN,NAILAH L.,Social Insurance Assistant I,6,PCARES,Casual,
MAMA,KHANIDA M.,Social Insurance Assistant I,6,PCARES,Casual,
MANGINSAY,KRSITINE MAE C.,Social Insurance Assistant I,6,PCARES,Casual,
MARAGUINOT,DEBBIE M.,Social Insurance Assistant I,6,PCARES,Casual,
MARCERA,EMMYLOU M.,Social Insurance Assistant I,6,PCARES,Casual,
MENDOZA,CEDRIC P.,Social Insurance Assistant I,6,PCARES,Casual,
MONTALBAN,MARIA EDEN G.,Social Insurance Assistant I,6,PCARES,Casual,
MONTEJO,BENJAM EMMANUEL B.,Social Insurance Assistant I,6,PCARES,Casual,
MORA,JOANA JOYCE T.,Social Insurance Assistant I,6,PCARES,Casual,
PEREZ,JET A.,Social Insurance Assistant I,6,PCARES,Casual,
RABANES,PAULO M.,Social Insurance Assistant I,6,PCARES,Casual,
RADIA,SITTIE NURHANISA N.,Social Insurance Assistant I,6,PCARES,Casual,
REVELO,GEOFREY C.,Social Insurance Assistant I,6,PCARES,Casual,
SADE,BRIAN JAY A.,Social Insurance Assistant I,6,PCARES,Casual,
UNSON,CHARLEMAGNE G.,Social Insurance Assistant I,6,PCARES,Casual,
UNSON,CHRISTIE PEARL L.,Social Insurance Assistant I,6,PCARES,Casual,
VENTE,NIKKA T.,Social Insurance Assistant I,6,PCARES,Casual,
VENTURA,QUENIE E.,Social Insurance Assistant I,6,PCARES,Casual,
VILLAVELEZ,CHLIENT JHUN A.,Social Insurance Assistant I,6,PCARES,Casual,
MAGLANGIT,JAYR P.,Social Insurance Assistant I,6,CPAMS,Casual,
MAMAT,ISRAEL B.,Administrative Aide VI,5,CPAMS,Casual,
MAROHOMBSAR,KASAN M. IV,Administrative Aide VI,5,CPAMS,Casual,
PINEDA,KYLE IVAN,Administrative Aide VI,5,CPAMS,Casual,
LUCMAN,SUMMIYAH B.,Courier,5,MMS,Casual,
PAGON,RANDY C.,Social Insurance Assistant I,6,MMS,Casual,
YACAPIN,ROY RAFAEL J.,Administrative Aide VI,5,MMS,Casual,
BAIÑO,ARVEJUNE T.,Administrative Aide VI,5,LHIO BUKIDNON,Casual,
CUYONG,ROXIN L.,Administrative Aide VI,5,LHIO BUKIDNON,Casual,
DE PEDRO,NEMFA S.,Social Insurance Assistant I,6,LHIO BUKIDNON,Casual,
EDMA,FIONA BLANCA N.,Courier,5,LHIO BUKIDNON,Casual,
ESTILLORE,CHERRY KATE B.,Administrative Aide VI,5,LHIO BUKIDNON,Casual,
LIMOCON,MARILOU B.,Courier,5,LHIO BUKIDNON,Casual,
MONTAYRE,WENDELL LLOYD C.,Administrative Aide VI,5,LHIO BUKIDNON,Casual,
MONTON,JOEL G.,Administrative Aide IV (Driver II),5,LHIO BUKIDNON,Casual,
RICHA,EMELIA MAE C.,Administrative Aide VI,5,LHIO BUKIDNON,Casual,
ALFANTA,EPHRAIM J.,Administrative Aide IV (Driver II),5,LHIO ILIGAN,Casual,
BATARA,MADED JR. M.,Social Insurance Officer II,9,LHIO ILIGAN,Casual,
BAYAS,ASNIMA A.,Social Insurance Assistant I,6,LHIO ILIGAN,Casual,
CASTILLANO,AIMEE LOREN G.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
DIMAPORO,KHADAPE T.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
ECOT,CHARIBEL N.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
ENDRIGA,METHUSELLA RHEA DC.,Social Insurance Assistant I,6,LHIO ILIGAN,Casual,
MABAYO,KAREEM MAE R.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
MAPANDI,JOHANNA B.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
TALLADA,JULIUS TRISTAN B.,Administrative Aide VI,5,LHIO ILIGAN,Casual,
VIEJO,EMMALY L.,Social Insurance Assistant I,6,LHIO ILIGAN,Casual,
CORDERO,ALFRENETH MAE G.,Administrative Aide VI,5,LHIO ILIGAN,Casual,PBC TUBOD
LICANDA,CHARLES ANGEL S.,Administrative Aide VI,5,LHIO ILIGAN,Casual,PBC LALA
SOBREPEÑA,JESS OLIVER G.,Administrative Aide VI,5,LHIO ILIGAN,Casual,PBC LALA
TAMPUS,AMELIZA V.,Administrative Aide VI,5,LHIO ILIGAN,Casual,PBC LALA
COMPACION,STARLITA PEARL L.,Social Insurance Assistant I,6,LHIO OZAMIZ,Casual,
DELA ROSA,KYSHA MELAN S.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
EGBUS,GLERALD A.,Courier,5,LHIO OZAMIZ,Casual,
ILAGAN,CHERYL P.,Social Insurance Assistant I,6,LHIO OZAMIZ,Casual,
ITABLE,NEZELME J.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
LABASTIDA,RICHILLETE T.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
MAKIG-ANGAY,JERYLEN V.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
MARTIR,LYRRAH LEI J.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
OGAO-OGAO,ANTHER P.,Social Insurance Assistant I,5,LHIO OZAMIZ,Casual,
SAAVEDRA,RIVA JOYCE T.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,
UCAB,WILLARD B.,Administrative Aide IV (Driver II),5,LHIO OZAMIZ,Casual,
CONING,KRISTINE U.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,PBC OROQUIETA
QUIZA,PETER DAVE V.,Courier,5,LHIO OZAMIZ,Casual,PBC OROQUIETA
TANCOGO,LUCILE L.,Administrative Aide VI,5,LHIO OZAMIZ,Casual,PBC TANGUB
ABDUL BASHET,JESSICA SYRA M.,Administrative Aide VI,5,LHIO CDO,Casual,
AGAPAY,JACKYLYN ROSE D.,Administrative Aide VI,5,LHIO CDO,Casual,
BONOAN,BAUTER S.,Administrative Aide VI,5,LHIO CDO,Casual,
CABALDA,DIANE GRACE L.,Social Insurance Assistant I,6,LHIO CDO,Casual,
CAGADAS,SHEILA MAE V.,Administrative Aide VI,5,LHIO CDO,Casual,
DAGOHOY,NIÑO BRYAN P.,Social Insurance Assistant I,5,LHIO CDO,Casual,
DENSING,APRIL MAE R.,Administrative Aide VI,5,LHIO CDO,Casual,
ENSENCIO,YVETTE KIDDYLOVE C.,Social Insurance Assistant I,6,LHIO CDO,Casual,
GRAVINA,VICTOR D.,Administrative Aide VI,5,LHIO CDO,Casual,
HERNANDEZ,ALAN ARKIN A.,Social Insurance Assistant I,6,LHIO CDO,Casual,
MANZANO,JAIME JACOBO D. JR.,Administrative Aide VI,5,LHIO CDO,Casual,
PACEÑO,STELLA MARIE M.,Administrative Aide VI,5,LHIO CDO,Casual,
ROXAS,JANETH MAY T.,Administrative Aide VI,5,LHIO CDO,Casual,
SAGUN,CHARO D.,Administrative Aide VI,5,LHIO CDO,Casual,
SANDOVAL,MARK ANTHONY L.,Courier,5,LHIO CDO,Casual,
SULTAN,MINAH BAE “JUNAYAH” B.,Administrative Aide VI,5,LHIO CDO,Casual,
TANTIADO,EIZEN C.,Administrative Aide VI,5,LHIO CDO,Casual,
TILAP,RAFAEL EDMOND R.,Administrative Aide VI,5,LHIO CDO,Casual,
YACAPIN,LIZA AMOR D.,Social Insurance Assistant I,6,LHIO CDO,Casual,
YONGCO,ARIES DABE E.,Administrative Aide IV (Driver II),5,LHIO CDO,Casual,
TANCONGCO,ODELYNNE C.,Administrative Aide VI,5,LHIO CDO,Casual,PBC CARMEN
CASINILLO,CATHERINE GLEN T.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
CERVANTES,KIRK ADRIAN B.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
DANO,JOHN PAUL S.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
FABE,FARRAH CORAZON R.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
FELISAN,JASPER JIM L.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
FORONES,DOROTEO JR. B.,Administrative Aide IV (Driver II),5,LHIO GINGOOG,Casual,
LIBAGO,XERXES N.,Courier,5,LHIO GINGOOG,Casual,
PORMINAL,LYDELL LOU C.,Social Insurance Assistant I,6,LHIO GINGOOG,Casual,
QUILOQUILO,KENN LEE B.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
RAMOSO,CHRISTINE CLARIZE MAE D.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
SANTIAGO,ALJEE L.,Social Insurance Assistant I,6,LHIO GINGOOG,Casual,
SUSUSCO,GERALDINE R.,Administrative Aide VI,5,LHIO GINGOOG,Casual,
OCLARIT,MARY JEAN J.,Administrative Aide VI,5,PBC CAMIGUIN,Casual,
CASIÑO,MICHAEL ANDREW M.,Administrative Aide VI,5,ORVP,Casual,
LAWAS,KLAUSMEINE,Courier,5,PAU,Casual,
ORIAS,PAMELA JAY F.,Courier,5,PAU,Casual,
ARELLANO-HUSSEIN,ALMIRA FLOR J.,Social Insurance Assistant I,6,LEGAL,Casual,
MACABATO,INTIZAR M.,Social Insurance Assistant I,6,LEGAL,Casual,
RIPORS,OMAR SHARIEF A.,Social Insurance Assistant I,6,LEGAL,Casual,
COTIAMCO,CARMEL JUN V.,Administrative Aide VI,5,ITMS,Casual,
MILLER,RICARDO JR. V.,Social Insurance Assistant I,6,ITMS,Casual,
PABUA,HARVEY D.,Social Insurance Assistant I,6,ITMS,Casual,
MACADAYA,PEPIRAKUN G.,Social Insurance Assistant I,6,PRU,Casual,
BAGUNDOL,ROSELLO M.,Computer Maintenance Technologist I,8,OMSD,Regular,
UY,MARY KAY J.,Fiscal Controller IV,12,OMSD,Regular,
LUCMAN,ANNA ALIA B.,Administrative Officer IV,12,ASS,Regular,
DALISAY,MARIA DULCE H.,Human Resource Mgt. Asst.,6,GSU,Regular,
DAYUHA,REYLAN D.,Administration Services Assistant C,6,GSU,Regular,
ELTANAL,GLADYS A.,Administrative Officer III,11,GSU,Regular,
FABELLO,WISA MARIE M.,Administration Services Officer II,9,GSU,Regular,
LUMAPAS,DENNIS A.,Administrative Officer I,8,GSU,Regular,
MARTINEZ,BEÑAPOL P.,Clerk III,5,GSU,Regular,
RUDINAS,JACKIE LOU G.,Administrative Officer I,10,GSU,Regular,
SERIÑA,CHERRY MAE G.,Administrative Officer II,10,GSU,Regular,
ESCABA,MANUEL LUIS JR. D.,Human Resource Management Officer I,8,HRU,Regular,
LOMONDOT,AISHA B.,Administration Services Assistant C,6,HRU,Regular,
MACALBE,ANNA JUNAYNAH A.,Human Resource Management Officer III,11,HRU,Regular,
POBLETE,RUMAR S.,Fiscal Clerk III,6,HRU,Regular,
AMAHOY,MARIA TERESA B.,Fiscal Controller III,11,FMS,Regular,
LUSICA,MARK ANTHONY A.,Fiscal Controller I,8,FMS,Regular,
VINATERO,MARY CAROLYN F.,Social Insurance Assistant II,7,FMS,Regular,
AMPASO,MARIAM S.,Financial Planning Assistant B,7,CU,Regular,
ASUM,ALIAH B.,Fiscal Examiner A,9,CU,Regular,
BALABA,MARLON JAN B.,Fiscal Clerk III,6,CU,Regular,
DALAGAN,DAIAN A.,Fiscal Controller II,10,CU,Regular,
UBAYUBAY,OWEN C.,Financial Planning Assistant B,7,CU,Regular,
BALINDONG,ASIZA D.,Fiscal Examiner A,9,CMU,Regular,
ELTANAL,KENNETH LLOYD S.,Fiscal Clerk III,6,CMU,Regular,
LATOSA,DEXTER S.,Fiscal Controller III,11,CMU,Regular,
ORTIGOZA,JONATHAN T.,Medical Officer VII,13,OHCDMD,Regular,
TUANGGANG,CHERRY ANN O.,Social Insurance Officer I,8,OHCDMD,Regular,
ALA,ALYANAH M.,Medical Specialist I,12,BAS,Regular,
BANTUAS,JOHANNA L.,Medical Specialist I,12,BAS,Regular,
BACARAMAN,MYLENE JOY M.,Clerk III,5,BAS,Regular,
CANOY,JANE C.,Social Insurance Assistant I,6,BAS,Regular,
HALASAN,ESMERALDA T.,Social Insurance Officer II,9,BAS,Regular,
LAO,EZNAIRAH A.,Medical Specialist IV,13,BAS,Regular,
LIM,GEO-ANN TRICIA P.,Social Insurance Assistant I,6,BAS,Regular,
MACALA,NAIDA D.,Social Insurance Officer I,8,BAS,Regular,
MAR,ARLENE JOY A.,Medical Specialist I,12,BAS,Regular,
MIKUNUG,AISAH S.,Social Insurance Assistant I,6,BAS,Regular,
OVALO,ERLYN T.,Social Insurance Officer I,8,BAS,Regular,
SALAS,ANTONIO FERNANDO M.,Social Insurance Assistant I,6,BAS,Regular,
TAMPI,ALEXANDER M.,Social Insurance Officer III,10,BAS,Regular,
TANCONGCO-SALOMA,JUNE ODILLE B.,Medical Specialist I,12,BAS,Regular,
EBIO,ANDREW I.,Social Insurance Officer II,9,AQAS,Regular,
JANIOLA,BEVERLY D.,Social Insurance Officer I,8,AQAS,Regular,
RAMOS,FRANCIS A.,Medical Specialist I,12,AQAS,Regular,
TAYROS,SHERRIE A.,Social Insurance Officer I,8,AQAS,Regular,
YAP,MAE DESIREE L.,Medical Specialist IV,13,AQAS,Regular,
BANAAG,VILLVEX A.,Fiscal Clerk III,6,OFOD,Regular,
DACUT,REMEA VERA R.,Special Investigator II,10,OFOD,Regular,
MONSANTO,MARIA RHODELLA S.,Division Chief IV,12,OFOD,Regular,
GUILING,FATMAH T.,Chief Social Insurance Officer,12,MMS,Regular,
MAROHOMBSAR,JAMILY D.,Social Insurance Officer II,9,MMS,Regular,
TIROL,MICHELLE A.,Social Insurance Officer I,8,MMS,Regular,
ASUM,KHALID M.,Chief Social Insurance Officer,12,CPAMS,Regular,
MAGAÑA,ANNALIZA U.,Social Insurance Assistant II,7,CPAMS,Regular,
SABIO,CONSUELO KARINA C.,Social Insurance Officer III,10,CPAMS,Regular,
SANTUYO,JOHN EMMANUEL P.,Social Insurance Officer II,9,CPAMS,Regular,
ACOSTA,MARLYN R.,Social Insurance Officer II,9,LHIO BUKIDNON,Regular,
BALCOS,KRISTIN LYRELLE A.,Social Insurance Assistant I,6,LHIO BUKIDNON,Regular,
CO,APRIL CAYE O.,Social Insurance Assistant I,6,LHIO BUKIDNON,Regular,
LAPUZ,ROMULO JR. M.,Chief Social Insurance Officer,12,LHIO BUKIDNON,Regular,
LOYLOY,JEANIFER L.,Fiscal Controller I,8,LHIO BUKIDNON,Regular,
OMAS-AS,MITUSELLA A.,Social Insurance Officer II,9,LHIO BUKIDNON,Regular,
TUBA,JERRIC B.,Social Insurance Assistant I,6,LHIO BUKIDNON,Regular,
VILLAGANTOL,MICHAEL L.,Social Insurance Assistant I,6,LHIO BUKIDNON,Regular,
JARABE,CLAUDETTE M.,Social Insurance Assistant I,6,LHIO BUKIDNON,Regular,PBC MALAYBALAY
PAGAURA,CIPRIANO C.,Social Insurance Officer III,10,LHIO BUKIDNON,Regular,PBC MALAYBALAY
CORTEZANO,GILBERT S.,Senior Social Insurance Officer,11,LHIO BUKIDNON,Regular,PBC MARAMAG
LAURE,ANA LIZA L.,Social Insurance Assistant II,7,LHIO BUKIDNON,Regular,PBC MARAMAG
ALI,ALEKSANDER A.,Fiscal Controller I,8,LHIO ILIGAN,Regular,
BUQUE,KAREN C.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
CAMPONG,SHALIMA S.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
DANGCAL,NORAIMA D.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
IBRAHIM,AIMI T.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
MACUMBAL,AYESAH M.,Social Insurance Officer III,10,LHIO ILIGAN,Regular,
MARTINEZ,GERARDO JR. B.,Social Insurance Assistant II,7,LHIO ILIGAN,Regular,
PADILLA,GIOVANNI B.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
PEÑARANDA,PATRICK C.,Executive Assistant II,10,LHIO ILIGAN,Regular,
SALAZAR,RAIZA D.,Social Insurance Assistant I,6,LHIO ILIGAN,Regular,
PABINGWIT,FLORIFE H.,Social Insurance Officer III,10,LHIO ILIGAN,Regular,PBC TUBOD
CABANG,GERION P.,Special Investigator II,10,LHIO OZAMIZ,Regular,
DEGAMO,FLORANTE S.,Social Insurance Assistant II,7,LHIO OZAMIZ,Regular,
JEAN,ROSALIE A.,Social Insurance Assistant II,7,LHIO OZAMIZ,Regular,
TAPITAN,DAISY A.,Social Insurance Assistant I,6,LHIO OZAMIZ,Regular,
VALENCIA,FROILAN C.,Social Insurance Officer II,9,LHIO OZAMIZ,Regular,
FLORES,JONATHAN L.,Social Insurance Officer III,10,LHIO OZAMIZ,Regular,PBC OROQUIETA
ALIP,ABDUL OBEDI S.,Social Insurance Officer III,10,LHIO CDO,Regular,
ARRABACA,MARLON NIÑO S.,Chief Social Insurance Officer,12,LHIO CDO,Regular,
CALI,SANALIAH B.,Social Insurance Assistant I,6,LHIO CDO,Regular,
DEREQUITO,ANGELIQUE A.,Social Insurance Assistant I,6,LHIO CDO,Regular,
DIANGCA,JUHARY S.,Clerk III,5,LHIO CDO,Regular,
DOMUGHO,EDNA MAE B.,Social Insurance Assistant I,6,LHIO CDO,Regular,
LABITAD,RIZALYN D.,Fiscal Controller I,8,LHIO CDO,Regular,
LAÑAS,HAZEL B.,Fiscal Controller I,8,LHIO CDO,Regular,
MAROHOMBSAR,KASAN III A.,Social Insurance Officer III,10,LHIO CDO,Regular,
NUÑEZ,RANILO P.,Social Insurance Assistant I,6,LHIO CDO,Regular,
RATUNIL,HAJJI RYAN STEPHEN A.,Social Insurance Assistant II,7,LHIO CDO,Regular,
BANTUAS,BOHARI D.,Social Insurance Officer I,8,LHIO CDO,Regular,PBC CARMEN
ARNAIZ,ANTONIO JR. A.,Chief Social Insurance Officer,12,LHIO GINGOOG,Regular,
BA-A,ROGER D.,Social Insurance Assistant I,6,LHIO GINGOOG,Regular,
CAINGLES,ELDA O.,Social Insurance Assistant II,7,LHIO GINGOOG,Regular,
OCTAVIO-ONDAP,SAHARA GAY S.,Social Insurance Officer II,9,LHIO GINGOOG,Regular,
CHAN,MARNI FATIMA E.,Social Insurance Officer I,8,LHIO GINGOOG,Regular,PBC CAMIGUIN
ASERON,DELIO II A.,Regional Vice President,14,ORVP,Regular,
MAGLANGIT,REX ODON O.,Administration Services Assistant C,6,ORVP,Regular,
REFORMA,SARAH L.,Senior Social Insurance Officer,11,ORVP,Regular,
RUIZ,ZIUR C.,Special Investigator IV,12,ORVP,Regular,
TOCAO,EVANDE MARIE L.,Public Relations Officer I,8,ORVP,Regular,
ENSUGO,GERMAINE B.,Special Investigator III,11,LEGAL,Regular,
GO,BON SAM ART V.,Legal Assistant I,7,LEGAL,Regular,
GUBAT,SITTIE AINAH A.,Special Investigator II,10,LEGAL,Regular,
MACAGAAN,NADER JR. L.,Special Investigator III,11,LEGAL,Regular,
MAGNO,IAN ALFREDO T.,Attorney IV,12,LEGAL,Regular,
MAPANDI,FARHANNA B.,Legal Researcher,9,LEGAL,Regular,
MONSANTO,RAUL ISABELO P.,Special Investigator III,11,LEGAL,Regular,
SAIBEN,FARHAN A.,Legal Researcher,9,LEGAL,Regular,
BORANSING,RAJIV AMIN ALISSANDRO M.,Social Insurance Officer I,8,ITMS,Regular,
RIMANDO,REYNALDO DENNIS P.,Information Technology Officer II,12,ITMS,Regular,
YBAÑEZ,MERLYN H.,Public Relations Officer III,11,PAU,Regular,
MANGONDATO,ANSHARI M.,Planning Officer III,11,PRU,Regular,
CSV;

        $lines = explode("\n", trim($csv));
        foreach ($lines as $line) {
            $data = str_getcsv($line);
            if (count($data) < 6) continue;

            Employee::create([
                'fullname' => $data[1] ? "{$data[1]} {$data[0]}" : $data[0],
                'designation' => $data[2],
                'salary_grade' => $data[3],
                'office_division' => $data[4],
                'employment_status' => strtoupper($data[5]) === 'REGULAR' ? 'PERMANENT' : strtoupper($data[5]),
                'sub_office' => ($data[6] ?? null) ?: null,
            ]);
        }
    }
}
